version: '3'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo17
      - POSTGRES_PASSWORD=odoo17
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    
    restart: always

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"

    restart: always

    volumes:
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo17
      - PASSWORD=odoo17
      - DATABASE=postgres
    command: ["odoo", "-c", "/etc/odoo/odoo.conf", "-u", "gestion_academica"]

volumes:
  odoo-db-data:
